Update utils.py
caesarHQ/textSQL pull request #60
Opened 2023-03-12 11:02 UTC by nrghosh

Don't want to let user input mess with table permissions on our side. Alternatively, we could just fix this at the session level with ```SET SESSION TRANSACTION READ ONLY;```

2023-03-12 20:08 UTC, alex-sun-kuo reviewed
@nrghosh thanks for the PR! do you want to also add a quick change to set this at the session level as you mentioned? sounds like that would be cleaner as well

2023-03-12 20:09 UTC, alex-sun-kuo requested changes
@nrghosh thanks for the PR! do you want to also add a quick change to set this at the session level as you mentioned? sounds like that would be cleaner as well

2023-03-13 05:30 UTC, nrghosh commented
@alex-sun-kuo done + merged in separate PR [see: https://github.com/caesarHQ/textSQL/pull/61 ]. It's not costly to filter the generated SQL statement against the blacklisted words so I didn't remove this section (checking, etc) entirely in the other PR -- so we could still merge this.

2023-03-13 09:10 UTC, alex-sun-kuo approved these changes

2023-03-13 09:11 UTC, merged